server:
  port: 8084
spring:
  application:
    name: @artifactId@
  cloud:
    stream:
      bindings:
        myInput:
          group: groupB
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/