spring:
  application:
    name: @artifactId@
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

---
server:
  port: 8081
spring:
  profiles: server-1

---
server:
  port: 8082
spring:
  profiles: server-2