server:
  port: 8085
spring:
  application:
    name: @artifactId@
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG