spring:
  application:
    name: @artifactId@
---
server:
  port: 8761
spring:
  profiles: server-1
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
---
server:
  port: 8762
spring:
  profiles: server-2
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/