server:
  port: 9411
zipkin:
  storage:
    type: mysql
spring:
  datasource:
    schema: classpath:/mysql.sql
    url: jdbc:mysql://localhost:3306/zk-server?autoReconnect=true&characterEncoding=utf-8
    username: root
    password: root
    initialize: true
    continueOnError: true